name: movie_app_project
description: "Mobile App Development - App Project"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  envied: ^0.5.4+1
  http: ^1.2.1
  tmdb_api: ^2.2.0
  get: ^4.6.6
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.3
  hive_ui: ^1.0.14
  carousel_slider: ^4.2.1
  intl: ^0.19.0
  flutter_svg: ^2.0.10+1
  flutter_native_splash: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.11

  flutter_lints: ^3.0.0

  envied_generator: ^0.5.4+1

  hive_generator: ^2.0.1

  flutter_launcher_icons: ^0.13.1

  mockito: ^5.4.4




flutter:
  uses-material-design: true
  assets:
    - assets/icon/icon.png
    - assets/images/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon_launcher_icon.png"
  min_sdk_android: 21
  remove_alpha_ios: true

flutter_native_splash:
  android: true
  ios: true
  color: "#151218"
  image: "assets/icon/icon.png"
  android_12:
    image: "assets/images/icon_scaled.png"
    color: "#151218"
    branding: assets/images/tmdb_short.png
